language: php

sudo: false

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: make test

matrix:
  fast_finish: true
