language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - curl --version
  - composer install --no-interaction --prefer-source --dev

script: make test

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
